### ISSUE TITLE
maxNumLen

### ISSUE THREAD

**Issue by svaflica** [Tka4uk-Andrei/SortAlgo#12]
Можно сделать функцию поиска максимального значения в массиве (Это если ты беззнаковые рассматриваешь, конечно), ибо тебе он нужен при сортировке подсчетом, и функцию подсчета количества разрядов числа и написать что-то вроде этого:
int maxNumOfRadix = radix(maxValueOfArray(arr, arrEnd))

**Comment by Tka4uk-Andrei** [comment]
максимальное (и минимальное) значение ищется только в одной функции.
maxNumLen - ищет наибольшее кол-во разрядов у чисел в массиве

**Comment by svaflica** [comment]
У максимального значения в массиве максимальное количество разрядов, так?
Поэтому можно создать функцию поиска макс. значения и другую для подсчета количества разрядов
А максимальное значение ты еще ищешь в другой сортировке, так что количество строчек там можно сократить
