### ISSUE TITLE
Point.h

### ISSUE THREAD

**Issue by svaflica** [Tka4uk-Andrei/SortAlgo#14]
Советую назвать передаваемые параметры единообразно
 friend bool operator == (const Point& p1, const Point& p2);
 friend bool operator > (const Point& p1, const Point& p2);
 friend bool operator < (const Point& p1, const Point& p2);
 friend bool operator >= (const Point& p1, const Point& p2);
 friend bool operator <= (const Point& p1, const Point& p2);

void Point::operator += (const Point &p2Point)
void Point::operator -= (const Point &p2Point);
Point Point::operator + (const Point &p2Point);
Point Point::operator - (const Point &p2Point);

**Comment by Tka4uk-Andrei** [comment]
Я не очень понял

**Comment by svaflica** [comment]
В одном месте ты называешь передаваемый параметр "p1" или "p2", в другом же случае "p2Point"

**Comment by Tka4uk-Andrei** [comment]
ок, заменил
