### ISSUE TITLE
Point.cpp

### ISSUE THREAD

**Issue by svaflica** [Tka4uk-Andrei/SortAlgo#16]
Либо ставим скобочки при return, либо нет. Выбери что-то одно. 

double Point::getRadiusVector() const
{
    return sqrt( x_ * x_ + y_ * y_ );
}

double Point::getDistance(const Point& b) const
{
    return(sqrt( (x_ - b.x_) * (x_ - b.x_) + (y_ - b.y_) * (y_ - b.y_) ));
}

**Comment by Tka4uk-Andrei** [comment]
ок, убрал
