### ISSUE TITLE
BubbleSort

### ISSUE THREAD

**Issue by svaflica** [Tka4uk-Andrei/SortAlgo#2]
Разве это пузырёк?
 Я даже погуглила благодаря тебе https://ru.wikipedia.org/wiki/Сортировка_пузырьком
Или это разновидность какая?

**Comment by svaflica** [comment]
(Я дурак)

**Comment by svaflica** [comment]
У тебя какой-то нетрадиционный пузырек, но ты поясни за него, лол

**Comment by Tka4uk-Andrei** [comment]
Он не нетрадиционный, он неправильный

**Comment by svaflica** [comment]
Я это и имела в виду, просто написала по-особенному
