### ISSUE TITLE
Передача длины в качестве параметра

### ISSUE THREAD

**Issue by svaflica** [Tka4uk-Andrei/SortAlgo#3]
По-моему, проще было бы передавать длину в качестве параметра, а не конец массива.
(Не вижу смысла в извращении, которое ты наворотил)

**Comment by svaflica** [comment]
Сижу и глаза на лоб лезут от того, что ты передаешь не известную тебе длину, а arr+5

**Comment by Tka4uk-Andrei** [comment]
это смещение указателя. Это нормально. STL алгоритм сортировки так и принимает параметры

**Comment by Tka4uk-Andrei** [comment]
И это не извращение

**Comment by svaflica** [comment]
Ну, ладно. Я уже увидела. Снова прости.
