### ISSUE TITLE
CMP

### ISSUE THREAD

**Issue by svaflica** [Tka4uk-Andrei/SortAlgo#4]
А это ход конем!

Мне понравился этот подход

**Comment by Tka4uk-Andrei** [comment]
Спасибо :)

**Comment by svaflica** [comment]
А шо це таке "assigned"?

**Comment by Tka4uk-Andrei** [comment]
Это где?

**Comment by svaflica** [comment]
Над моим последним сообщением небольшая строка

**Comment by Tka4uk-Andrei** [comment]
Потому и спрашиваю. В Cmp этого нет 0_o

**Comment by svaflica** [comment]
Ладно

**Comment by Tka4uk-Andrei** [comment]
Немного изменил Cmp() теперь он возвращает bool

**Comment by svaflica** [comment]
Не вижу изменений в функции или ты не залил еще?

**Comment by Tka4uk-Andrei** [comment]
Залил
